class Any:
    pass

class Iterator:
    def __class_getitem__(cls, item) -> Any: ...
    def __next__(self) -> Any: ...

class Awaitable:
    def __class_getitem__(cls, item) -> Any: ...
    def __await__(self) -> Iterator: ...

class AsyncIterator:
    def __class_getitem__(cls, item) -> Any: ...
    def __anext__(self) -> Awaitable: ...

class Sized:
    def __len__(self) -> int: ...

class Iterable:
    def __class_getitem__(cls, item) -> Any: ...
    def __iter__(self) -> Iterator: ...

class Reversible(Iterable):
    def __class_getitem__(cls, item) -> Any: ...
    def __reversed__(self) -> Iterator: ...

class Sequence:
    def __class_getitem__(cls, item) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Iterator: ...
    def count(self, item: object) -> int: ...
    def index(self, item: object) -> int: ...

class Mapping:
    def __class_getitem__(cls, item) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __iter__(self) -> Iterator: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...
    def get(self, key: Any, default) -> Any: ...

class Callable:
    def __class_getitem__(cls, item) -> Any: ...
    def __call__(self) -> Any: ...

class Buffer:
    pass

class AsyncIterable:
    def __class_getitem__(cls, item) -> Any: ...
    def __aiter__(self) -> AsyncIterator: ...

class AsyncGenerator:
    def __class_getitem__(cls, item) -> Any: ...
    def asend(self, value: Any) -> Awaitable: ...
    def athrow(self, typ: Any, val: Any, tb: Any) -> Awaitable: ...
    def aclose(self) -> Awaitable: ...
