[project]
src = ["src"]
target_python = "3.10"

[typing]
profile = "application"
strict = false
strict_nulls = true

[emit]
emit_pyi = true
no_emit_on_error = true

[experimental]
accepted_features = ["framework_adapters"]
