class IOBase:
    def close(self) -> None: ...

class TextIOBase(IOBase):
    def read(self) -> str: ...
    def write(self, text: str) -> int: ...

class BufferedIOBase(IOBase):
    def read(self) -> bytes: ...
    def write(self, data: bytes) -> int: ...
