class Pattern:
    def match(self, text: str): ...
    def search(self, text: str): ...

class Match:
    def group(self, index=0): ...

def compile(pattern: str) -> Pattern: ...
def match(pattern: str, text: str): ...
def search(pattern: str, text: str): ...
