class Any:
    pass

class Optional:
    pass

class Union:
    pass

class Callable:
    pass

class Literal:
    pass

class Annotated:
    pass

class TypedDict:
    pass

class Protocol:
    pass

class Iterator:
    def __next__(self) -> Any: ...

class Awaitable(Protocol):
    def __await__(self) -> Iterator: ...

class AsyncIterable(Protocol):
    def __aiter__(self) -> AsyncIterator: ...

class AsyncIterator(AsyncIterable):
    def __anext__(self) -> Awaitable: ...

class AsyncGenerator(AsyncIterator):
    def asend(self, value: Any) -> Awaitable: ...
    def athrow(self, typ: Any, val: Any, tb: Any) -> Awaitable: ...
    def aclose(self) -> Awaitable: ...

class Coroutine(Awaitable):
    def send(self, value: Any) -> Any: ...
    def throw(self, typ: Any, val: Any, tb: Any) -> Any: ...
    def close(self) -> None: ...

class Generator(Iterator):
    def send(self, value: Any) -> Any: ...
    def throw(self, typ: Any, val: Any, tb: Any) -> Any: ...
    def close(self) -> None: ...

def cast(t, value) -> Any: ...
def NewType(name: str, typ) -> Any: ...
def TypeVar(name: str) -> Any: ...
def ParamSpec(name: str) -> Any: ...
def TypeVarTuple(name: str) -> Any: ...
