[package]
name = "typepython-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
typepython-emit = { path = "../crates/typepython_emit" }
typepython-lowering = { path = "../crates/typepython_lowering" }
typepython-syntax = { path = "../crates/typepython_syntax" }

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "type_expr"
path = "fuzz_targets/type_expr.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lowering_stub"
path = "fuzz_targets/lowering_stub.rs"
test = false
doc = false
bench = false
