use std::{fs, path::Path, process::ExitCode};

use anyhow::{Context, Result};
use serde::Serialize;
use typepython_diagnostics::{Diagnostic, DiagnosticReport};

use crate::{
    CommandSummary,
    cli::{OutputFormat, TypeHealthArgs},
    exit_code, load_project, print_summary,
};

#[derive(Debug, Clone, Eq, PartialEq, Serialize)]
pub(crate) struct TypeHealthReport {
    pub(crate) score: u8,
    pub(crate) packages: Vec<TypePackageHealth>,
    pub(crate) lock_path: Option<String>,
}

#[derive(Debug, Clone, Eq, PartialEq, Serialize)]
pub(crate) struct TypePackageHealth {
    pub(crate) name: String,
    pub(crate) root: String,
    pub(crate) has_py_typed: bool,
    pub(crate) is_stub_only: bool,
    pub(crate) is_partial_stub: bool,
}

pub(crate) fn run_type_health(args: TypeHealthArgs) -> Result<ExitCode> {
    let config = load_project(args.run.project.as_ref())?;
    let mut report =
        build_type_health_report(&config.config_dir, &config.config.resolution.type_roots)?;
    if args.write_lock {
        let lock_path = config.config_dir.join(".typepython/type-lock.toml");
        write_type_lock(&lock_path, &report)?;
        report.lock_path = Some(lock_path.display().to_string());
    }

    let mut diagnostics = DiagnosticReport::default();
    if let Some(threshold) = args.fail_under
        && report.score < threshold
    {
        diagnostics.push(Diagnostic::error(
            "TPY7002",
            format!("type health score {} is below required threshold {threshold}", report.score),
        ));
    }

    if args.run.format == OutputFormat::Json {
        let payload = serde_json::json!({ "summary": report, "diagnostics": diagnostics });
        println!(
            "{}",
            serde_json::to_string_pretty(&payload)
                .context("unable to serialize type-health report")?
        );
    } else {
        print_type_health_text(&report);
        let summary = CommandSummary {
            command: String::from("type-health"),
            config_path: config.config_path.display().to_string(),
            config_source: config.source,
            discovered_sources: report.packages.len(),
            lowered_modules: 0,
            planned_artifacts: usize::from(args.write_lock),
            tracked_modules: report
                .packages
                .iter()
                .filter(|package| package.has_py_typed || package.is_stub_only)
                .count(),
            notes: vec![String::from(
                "inspected configured resolution.type_roots for PEP 561 typing metadata",
            )],
        };
        print_summary(args.run.format, &summary, &diagnostics)?;
    }
    Ok(exit_code(&diagnostics))
}

pub(crate) fn build_type_health_report(
    config_dir: &Path,
    type_roots: &[String],
) -> Result<TypeHealthReport> {
    let mut packages = Vec::new();
    for root in type_roots {
        let root_path = config_dir.join(root);
        if !root_path.is_dir() {
            continue;
        }
        for entry in fs::read_dir(&root_path)
            .with_context(|| format!("unable to read {}", root_path.display()))?
        {
            let path = entry?.path();
            if path.is_dir() {
                packages.push(package_health(&path)?);
            }
        }
    }
    packages.sort_by(|left, right| left.name.cmp(&right.name));
    let typed =
        packages.iter().filter(|package| package.has_py_typed || package.is_stub_only).count();
    let score = if packages.is_empty() { 100 } else { ((typed * 100) / packages.len()) as u8 };
    Ok(TypeHealthReport { score, packages, lock_path: None })
}

fn package_health(path: &Path) -> Result<TypePackageHealth> {
    let file_name = path.file_name().and_then(|name| name.to_str()).unwrap_or_default();
    let py_typed = path.join("py.typed");
    let marker = fs::read_to_string(&py_typed).unwrap_or_default();
    Ok(TypePackageHealth {
        name: file_name.trim_end_matches("-stubs").to_owned(),
        root: path.display().to_string(),
        has_py_typed: py_typed.exists() && !file_name.ends_with("-stubs"),
        is_stub_only: file_name.ends_with("-stubs"),
        is_partial_stub: marker.lines().any(|line| line.trim() == "partial"),
    })
}

fn write_type_lock(path: &Path, report: &TypeHealthReport) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("unable to create {}", parent.display()))?;
    }
    let mut rendered = String::from("# Generated by typepython type-health --write-lock\n");
    rendered.push_str(&format!("score = {}\n\n", report.score));
    for package in &report.packages {
        rendered.push_str("[[package]]\n");
        rendered.push_str(&format!("name = \"{}\"\n", package.name));
        rendered.push_str(&format!("root = \"{}\"\n", package.root.replace('\\', "\\\\")));
        rendered.push_str(&format!("has_py_typed = {}\n", package.has_py_typed));
        rendered.push_str(&format!("is_stub_only = {}\n", package.is_stub_only));
        rendered.push_str(&format!("is_partial_stub = {}\n\n", package.is_partial_stub));
    }
    fs::write(path, rendered).with_context(|| format!("unable to write {}", path.display()))
}

fn print_type_health_text(report: &TypeHealthReport) {
    println!("type-health:");
    println!("  score: {}", report.score);
    for package in &report.packages {
        println!(
            "  package: {} py.typed={} stub_only={} partial={}",
            package.name, package.has_py_typed, package.is_stub_only, package.is_partial_stub
        );
    }
    if let Some(lock_path) = &report.lock_path {
        println!("  lock: {lock_path}");
    }
}
