use super::*;

#[allow(dead_code)]
fn rewrite_to_stub_source(python: &str) -> Result<String, io::Error> {
    let module = LoweredModule {
        source_path: PathBuf::new(),
        source_kind: SourceKind::TypePython,
        python_source: python.to_owned(),
        source_map: Vec::new(),
        span_map: Vec::new(),
        required_imports: Vec::new(),
        metadata: typepython_lowering::LoweringMetadata::default(),
    };
    generate_typepython_stub_source(&module, &TypePythonStubContext::default())
}

/// Generates the authoritative `.pyi` surface for a lowered TypePython module.
pub fn generate_typepython_stub_source(
    module: &LoweredModule,
    context: &TypePythonStubContext,
) -> Result<String, io::Error> {
    let python = &module.python_source;
    let parsed = parse_module(python).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("unable to parse lowered Python for stub emission: {}", error.error),
        )
    })?;

    let lowered_context = LoweredStubContext::from_module(module, context);
    let mut edits = Vec::new();
    collect_authoritative_stub_edits(python, parsed.suite(), &lowered_context, &mut edits);
    edits.sort_by_key(|edit| edit.start_line);

    let lines: Vec<&str> = python.lines().collect();
    let mut output = Vec::new();
    let mut line = 1usize;
    let mut edits = edits.into_iter().peekable();

    while line <= lines.len() {
        if let Some(edit) = edits.peek()
            && edit.start_line == line
        {
            if let Some(replacement) = &edit.replacement {
                output.push(replacement.clone());
            }
            line = edit.end_line + 1;
            edits.next();
            continue;
        }

        output.push(lines[line - 1].to_owned());
        line += 1;
    }

    let mut rewritten = output.join("\n");
    rewritten =
        inject_guarded_declaration_stubs(python, parsed.suite(), &lowered_context, &rewritten);
    if python.ends_with('\n') {
        rewritten.push('\n');
    }
    normalize_emitted_stub_intrinsic_types(&rewritten)
}

/// Generates a best-effort `.pyi` surface for a pass-through Python module.
pub fn generate_inferred_stub_source(
    python: &str,
    mode: InferredStubMode,
) -> Result<String, io::Error> {
    let parsed = parse_module(python).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("unable to parse Python source for inferred stub emission: {}", error.error),
        )
    })?;

    let context = StubInferenceContext::from_suite(python, parsed.suite());
    let mut edits = Vec::new();
    collect_inferred_stub_edits(python, parsed.suite(), &context, mode, &mut edits);
    edits.sort_by_key(|edit| edit.start_line);

    let lines: Vec<&str> = python.lines().collect();
    let mut output = Vec::new();
    let mut line = 1usize;
    let mut edits = edits.into_iter().peekable();

    while line <= lines.len() {
        if let Some(edit) = edits.peek()
            && edit.start_line == line
        {
            if let Some(replacement) = &edit.replacement {
                output.push(replacement.clone());
            }
            line = edit.end_line + 1;
            edits.next();
            continue;
        }

        output.push(lines[line - 1].to_owned());
        line += 1;
    }

    let mut rewritten = output.join("\n");
    if mode == InferredStubMode::Migration {
        rewritten = if rewritten.is_empty() {
            String::from("# auto-generated by typepython migrate\n")
        } else {
            format!("# auto-generated by typepython migrate\n\n{rewritten}")
        };
    }
    if python.ends_with('\n') {
        rewritten.push('\n');
    }
    Ok(rewritten)
}

#[derive(Debug, Clone, Default)]
struct StubInferenceContext {
    class_names: std::collections::BTreeSet<String>,
    value_bindings: BTreeMap<String, String>,
    instance_attributes: BTreeMap<String, String>,
    receiver_name: Option<String>,
}

impl StubInferenceContext {
    fn from_suite(source: &str, suite: &[Stmt]) -> Self {
        let class_names = suite
            .iter()
            .filter_map(|statement| match statement {
                Stmt::ClassDef(class_def) => Some(class_def.name.as_str().to_owned()),
                _ => None,
            })
            .collect();
        let mut context = Self {
            class_names,
            value_bindings: BTreeMap::new(),
            instance_attributes: BTreeMap::new(),
            receiver_name: None,
        };
        collect_name_bindings_from_suite(source, suite, &mut context);
        context
    }

    fn with_instance_attributes(&self, instance_attributes: BTreeMap<String, String>) -> Self {
        let mut derived = self.clone();
        derived.instance_attributes = instance_attributes;
        derived
    }

    fn with_receiver_name(&self, receiver_name: Option<&str>) -> Self {
        let mut derived = self.clone();
        derived.receiver_name = receiver_name.map(str::to_owned);
        derived
    }
}

fn collect_name_bindings_from_suite(
    source: &str,
    suite: &[Stmt],
    context: &mut StubInferenceContext,
) {
    for statement in suite {
        collect_name_bindings_from_statement(source, statement, context);
    }
}

fn collect_name_bindings_from_statement(
    source: &str,
    statement: &Stmt,
    context: &mut StubInferenceContext,
) {
    match statement {
        Stmt::Assign(assign) => {
            let Some(inferred) = infer_expr_type(&assign.value, context) else {
                return;
            };
            for target in &assign.targets {
                if let Expr::Name(name) = target {
                    context.value_bindings.insert(name.id.as_str().to_owned(), inferred.clone());
                } else if let Some(receiver_name) = context.receiver_name.as_deref()
                    && let Some(attribute) = self_attribute_name(target, receiver_name)
                {
                    context.instance_attributes.insert(attribute.to_owned(), inferred.clone());
                }
            }
        }
        Stmt::AnnAssign(assign) => {
            let Some(annotation) =
                slice_range(source, assign.annotation.range()).map(str::to_owned)
            else {
                return;
            };
            if let Expr::Name(name) = assign.target.as_ref() {
                context.value_bindings.insert(name.id.as_str().to_owned(), annotation);
            } else if let Some(receiver_name) = context.receiver_name.as_deref()
                && let Some(attribute) = self_attribute_name(assign.target.as_ref(), receiver_name)
            {
                context.instance_attributes.insert(attribute.to_owned(), annotation);
            }
        }
        _ => {}
    }
}

fn collect_inferred_stub_edits(
    source: &str,
    suite: &[Stmt],
    context: &StubInferenceContext,
    mode: InferredStubMode,
    edits: &mut Vec<StubEdit>,
) {
    for statement in suite {
        match statement {
            Stmt::FunctionDef(function) => {
                let start_line = offset_to_line(source, function.name.range.start().to_usize());
                let end_offset = function.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(function.range.start().to_usize()));
                edits.push(StubEdit {
                    start_line,
                    end_line,
                    replacement: Some(render_function_stub(source, function, false, context, mode)),
                });
            }
            Stmt::Assign(assign) => {
                let start_line = offset_to_line(source, assign.range.start().to_usize());
                let end_offset = assign.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(assign.range.start().to_usize()));
                if let Some(replacement) =
                    render_assignment_stub(source, &assign.targets, &assign.value, context, mode)
                {
                    edits.push(StubEdit { start_line, end_line, replacement: Some(replacement) });
                }
            }
            Stmt::AnnAssign(assign) => {
                let start_line = offset_to_line(source, assign.range.start().to_usize());
                let end_offset = assign.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(assign.range.start().to_usize()));
                if let Some(replacement) = render_annotated_assignment_stub(source, assign) {
                    edits.push(StubEdit { start_line, end_line, replacement: Some(replacement) });
                }
            }
            Stmt::ClassDef(class_def) => {
                let start_line = offset_to_line(source, class_def.name.range.start().to_usize());
                let end_offset = class_def.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(class_def.range.start().to_usize()));
                edits.push(StubEdit {
                    start_line,
                    end_line,
                    replacement: Some(render_class_stub(source, class_def, context, mode)),
                });
            }
            _ => {}
        }
    }
}

fn render_function_stub(
    source: &str,
    function: &ruff_python_ast::StmtFunctionDef,
    in_class: bool,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> String {
    render_function_stub_parts(
        source,
        function.name.as_str(),
        &function.parameters,
        function.returns.as_deref(),
        &function.body,
        in_class,
        function.is_async,
        is_static_method(&function.decorator_list),
        context,
        mode,
        function.name.range.start().to_usize(),
    )
}

#[allow(clippy::too_many_arguments)]
fn render_function_stub_parts(
    source: &str,
    name: &str,
    parameters: &ruff_python_ast::Parameters,
    returns: Option<&Expr>,
    body: &[Stmt],
    in_class: bool,
    is_async: bool,
    is_static_method: bool,
    context: &StubInferenceContext,
    mode: InferredStubMode,
    start_offset: usize,
) -> String {
    let def_line = offset_to_line(source, start_offset);
    let indent = leading_indent(source.lines().nth(def_line.saturating_sub(1)).unwrap_or(""));
    let (params, used_placeholder) =
        render_parameter_list(source, parameters, in_class, is_static_method, context, mode);
    let (return_annotation, missing_return) = match returns
        .and_then(|annotation| slice_range(source, annotation.range()))
        .map(str::to_owned)
    {
        Some(annotation) => (annotation, false),
        None => {
            let inferred = if is_async {
                None
            } else {
                infer_function_return_type(
                    source,
                    parameters,
                    body,
                    in_class,
                    is_static_method,
                    context,
                )
            };
            match inferred {
                Some(annotation) if annotation == missing_type_annotation(mode) => {
                    (annotation, true)
                }
                Some(annotation) => (annotation, false),
                None => (missing_type_annotation(mode).to_owned(), true),
            }
        }
    };
    let mut lines = Vec::new();
    if mode == InferredStubMode::Migration && (used_placeholder || missing_return) {
        lines.push(format!("{indent}# TODO: add type annotation"));
    }
    lines.push(format!(
        "{indent}{}def {}({}) -> {}: ...",
        if is_async { "async " } else { "" },
        name,
        params,
        return_annotation
    ));
    lines.join("\n")
}

fn render_parameter_list(
    source: &str,
    parameters: &ruff_python_ast::Parameters,
    in_class: bool,
    is_static_method: bool,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> (String, bool) {
    let mut parts = Vec::new();
    let mut missing = false;
    let mut parameter_index = 0usize;

    for parameter in &parameters.posonlyargs {
        let (text, parameter_missing) = render_parameter(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            parameter.default(),
            if parameter_index == 0 && in_class && !is_static_method {
                ReceiverKind::Implicit
            } else {
                ReceiverKind::None
            },
            ParameterPrefix::None,
            context,
            mode,
        );
        parts.push(text);
        missing |= parameter_missing;
        parameter_index += 1;
    }
    if !parameters.posonlyargs.is_empty() {
        parts.push(String::from("/"));
    }

    for parameter in &parameters.args {
        let (text, parameter_missing) = render_parameter(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            parameter.default(),
            if parameter_index == 0 && in_class && !is_static_method {
                ReceiverKind::Implicit
            } else {
                ReceiverKind::None
            },
            ParameterPrefix::None,
            context,
            mode,
        );
        parts.push(text);
        missing |= parameter_missing;
        parameter_index += 1;
    }

    if let Some(parameter) = parameters.vararg.as_ref() {
        let (text, parameter_missing) = render_parameter(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            None,
            ReceiverKind::None,
            ParameterPrefix::Variadic,
            context,
            mode,
        );
        parts.push(text);
        missing |= parameter_missing;
    } else if !parameters.kwonlyargs.is_empty() {
        parts.push(String::from("*"));
    }

    for parameter in &parameters.kwonlyargs {
        let (text, parameter_missing) = render_parameter(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            parameter.default(),
            ReceiverKind::None,
            ParameterPrefix::None,
            context,
            mode,
        );
        parts.push(text);
        missing |= parameter_missing;
    }

    if let Some(parameter) = parameters.kwarg.as_ref() {
        let (text, parameter_missing) = render_parameter(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            None,
            ReceiverKind::None,
            ParameterPrefix::KeywordVariadic,
            context,
            mode,
        );
        parts.push(text);
        missing |= parameter_missing;
    }

    (parts.join(", "), missing)
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
enum ReceiverKind {
    None,
    Implicit,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
enum ParameterPrefix {
    None,
    Variadic,
    KeywordVariadic,
}

#[allow(clippy::too_many_arguments)]
fn render_parameter(
    source: &str,
    name: &str,
    annotation: Option<&Expr>,
    default: Option<&Expr>,
    receiver: ReceiverKind,
    prefix: ParameterPrefix,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> (String, bool) {
    let prefix_text = match prefix {
        ParameterPrefix::None => "",
        ParameterPrefix::Variadic => "*",
        ParameterPrefix::KeywordVariadic => "**",
    };

    if receiver == ReceiverKind::Implicit && annotation.is_none() {
        return (
            format!("{prefix_text}{name}{}", if default.is_some() { " = ..." } else { "" }),
            false,
        );
    }

    let (annotation, missing) = match annotation
        .and_then(|annotation| slice_range(source, annotation.range()))
        .map(str::to_owned)
    {
        Some(annotation) => (annotation, false),
        None => match default.and_then(|value| infer_expr_type(value, context)) {
            Some(annotation) => (annotation, false),
            None => (missing_type_annotation(mode).to_owned(), true),
        },
    };

    (
        format!(
            "{prefix_text}{name}: {annotation}{}",
            if default.is_some() { " = ..." } else { "" }
        ),
        missing,
    )
}

fn render_assignment_stub(
    _source: &str,
    targets: &[Expr],
    value: &Expr,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> Option<String> {
    let mut lines = Vec::new();
    let inferred = infer_expr_type(value, context);
    for target in targets {
        if let Expr::Name(name) = target {
            let missing =
                inferred.is_none() || inferred.as_deref() == Some(missing_type_annotation(mode));
            if mode == InferredStubMode::Migration && missing {
                lines.push(String::from("# TODO: add type annotation"));
            }
            lines.push(format!(
                "{}: {}",
                name.id.as_str(),
                inferred.clone().unwrap_or_else(|| missing_type_annotation(mode).to_owned())
            ));
        }
    }
    (!lines.is_empty()).then(|| lines.join("\n"))
}

fn render_annotated_assignment_stub(
    source: &str,
    assign: &ruff_python_ast::StmtAnnAssign,
) -> Option<String> {
    let Expr::Name(name) = assign.target.as_ref() else {
        return None;
    };
    let annotation = slice_range(source, assign.annotation.range())?;
    Some(format!("{}: {}", name.id.as_str(), annotation))
}

fn render_class_stub(
    source: &str,
    class_def: &ruff_python_ast::StmtClassDef,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> String {
    let header =
        source_header_text(source, class_def.name.range.start().to_usize(), &class_def.body)
            .trim_end()
            .to_owned();
    let inferred_instance_attributes = infer_instance_attributes(source, class_def, context, mode);
    let mut body_lines = Vec::new();
    let mut known_instance_attributes =
        inferred_instance_attributes.iter().cloned().collect::<BTreeMap<_, _>>();
    let mut declared_names = std::collections::BTreeSet::new();

    for statement in &class_def.body {
        match statement {
            Stmt::AnnAssign(assign) => {
                let Expr::Name(name) = assign.target.as_ref() else {
                    continue;
                };
                let Some(annotation) = slice_range(source, assign.annotation.range()) else {
                    continue;
                };
                declared_names.insert(name.id.as_str().to_owned());
                known_instance_attributes
                    .insert(name.id.as_str().to_owned(), annotation.to_owned());
                body_lines.push(format!("    {}: {}", name.id.as_str(), annotation));
            }
            Stmt::Assign(assign) => {
                let inferred = infer_expr_type(&assign.value, context);
                for target in &assign.targets {
                    let Expr::Name(name) = target else {
                        continue;
                    };
                    declared_names.insert(name.id.as_str().to_owned());
                    if let Some(inferred) = &inferred {
                        known_instance_attributes
                            .insert(name.id.as_str().to_owned(), inferred.clone());
                    }
                    if mode == InferredStubMode::Migration
                        && (inferred.is_none()
                            || inferred.as_deref() == Some(missing_type_annotation(mode)))
                    {
                        body_lines.push(String::from("    # TODO: add type annotation"));
                    }
                    body_lines.push(format!(
                        "    {}: {}",
                        name.id.as_str(),
                        inferred
                            .clone()
                            .unwrap_or_else(|| missing_type_annotation(mode).to_owned())
                    ));
                }
            }
            Stmt::FunctionDef(function) => {
                let method_context =
                    context.with_instance_attributes(known_instance_attributes.clone());
                body_lines.push(render_method_with_decorators(
                    source,
                    function,
                    &method_context,
                    mode,
                ))
            }
            Stmt::ClassDef(nested) => {
                body_lines.push(render_class_stub(source, nested, context, mode))
            }
            _ => {}
        }
    }

    for (name, annotation) in inferred_instance_attributes {
        if declared_names.contains(&name) {
            continue;
        }
        if mode == InferredStubMode::Migration && annotation == missing_type_annotation(mode) {
            body_lines.push(String::from("    # TODO: add type annotation"));
        }
        body_lines.push(format!("    {name}: {annotation}"));
    }

    if body_lines.is_empty() {
        body_lines.push(String::from("    ..."));
    }

    format!("{header}\n{}", body_lines.join("\n"))
}

fn render_method_with_decorators(
    source: &str,
    function: &ruff_python_ast::StmtFunctionDef,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> String {
    let mut parts =
        decorator_lines(source, &function.decorator_list, function.name.range.start().to_usize());
    parts.push(render_function_stub(source, function, true, context, mode));
    parts.join("\n")
}

fn decorator_lines(
    source: &str,
    decorators: &[ruff_python_ast::Decorator],
    start_offset: usize,
) -> Vec<String> {
    let Some(first) = decorators.first() else {
        return Vec::new();
    };
    let start_line = offset_to_line(source, first.expression.range().start().to_usize());
    let end_line = offset_to_line(source, start_offset).saturating_sub(1);
    if start_line > end_line {
        return Vec::new();
    }
    source
        .lines()
        .skip(start_line.saturating_sub(1))
        .take(end_line.saturating_sub(start_line) + 1)
        .map(str::to_owned)
        .collect()
}

fn is_static_method(decorators: &[ruff_python_ast::Decorator]) -> bool {
    decorators.iter().any(|decorator| match &decorator.expression {
        Expr::Name(name) => name.id.as_str() == "staticmethod",
        Expr::Attribute(attribute) => attribute.attr.as_str() == "staticmethod",
        _ => false,
    })
}

fn first_receiver_name(parameters: &ruff_python_ast::Parameters) -> &str {
    if let Some(parameter) = parameters.posonlyargs.first() {
        parameter.name().as_str()
    } else if let Some(parameter) = parameters.args.first() {
        parameter.name().as_str()
    } else {
        "self"
    }
}

fn leading_indent(line: &str) -> String {
    line.chars().take_while(|character| character.is_whitespace()).collect()
}

fn missing_type_annotation(mode: InferredStubMode) -> &'static str {
    match mode {
        InferredStubMode::Shadow => "unknown",
        InferredStubMode::Migration => "...",
    }
}

fn infer_function_return_type(
    source: &str,
    parameters: &ruff_python_ast::Parameters,
    body: &[Stmt],
    in_class: bool,
    is_static_method: bool,
    context: &StubInferenceContext,
) -> Option<String> {
    let mut inferred = Vec::new();
    let mut unresolved = false;
    let function_context =
        build_function_inference_context(source, parameters, in_class, is_static_method, context);
    collect_return_annotations(source, body, &function_context, &mut inferred, &mut unresolved);
    if unresolved {
        return None;
    }
    if inferred.is_empty() { Some(String::from("None")) } else { normalize_union_types(inferred) }
}

fn build_function_inference_context(
    source: &str,
    parameters: &ruff_python_ast::Parameters,
    in_class: bool,
    is_static_method: bool,
    context: &StubInferenceContext,
) -> StubInferenceContext {
    let receiver_name = (in_class && !is_static_method).then(|| first_receiver_name(parameters));
    let mut function_context = context.with_receiver_name(receiver_name);
    let mut parameter_index = 0usize;
    for parameter in &parameters.posonlyargs {
        bind_parameter_inference(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            parameter.default(),
            if parameter_index == 0 && in_class && !is_static_method {
                ReceiverKind::Implicit
            } else {
                ReceiverKind::None
            },
            ParameterPrefix::None,
            &mut function_context,
        );
        parameter_index += 1;
    }
    for parameter in &parameters.args {
        bind_parameter_inference(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            parameter.default(),
            if parameter_index == 0 && in_class && !is_static_method {
                ReceiverKind::Implicit
            } else {
                ReceiverKind::None
            },
            ParameterPrefix::None,
            &mut function_context,
        );
        parameter_index += 1;
    }
    if let Some(parameter) = parameters.vararg.as_ref() {
        bind_parameter_inference(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            None,
            ReceiverKind::None,
            ParameterPrefix::Variadic,
            &mut function_context,
        );
    }
    for parameter in &parameters.kwonlyargs {
        bind_parameter_inference(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            parameter.default(),
            ReceiverKind::None,
            ParameterPrefix::None,
            &mut function_context,
        );
    }
    if let Some(parameter) = parameters.kwarg.as_ref() {
        bind_parameter_inference(
            source,
            parameter.name().as_str(),
            parameter.annotation(),
            None,
            ReceiverKind::None,
            ParameterPrefix::KeywordVariadic,
            &mut function_context,
        );
    }
    function_context
}

fn bind_parameter_inference(
    source: &str,
    name: &str,
    annotation: Option<&Expr>,
    default: Option<&Expr>,
    receiver: ReceiverKind,
    prefix: ParameterPrefix,
    context: &mut StubInferenceContext,
) {
    let inferred = match annotation
        .and_then(|annotation| slice_range(source, annotation.range()))
        .map(str::to_owned)
    {
        Some(annotation) => Some(annotation),
        None if receiver == ReceiverKind::Implicit => None,
        None => default.and_then(|value| infer_expr_type(value, context)),
    };
    let Some(inferred) = inferred else {
        return;
    };
    let binding = match prefix {
        ParameterPrefix::None => inferred,
        ParameterPrefix::Variadic => format!("tuple[{inferred}, ...]"),
        ParameterPrefix::KeywordVariadic => format!("dict[str, {inferred}]"),
    };
    context.value_bindings.insert(name.to_owned(), binding);
}

fn collect_return_annotations(
    source: &str,
    suite: &[Stmt],
    context: &StubInferenceContext,
    inferred: &mut Vec<String>,
    unresolved: &mut bool,
) {
    let mut local_context = context.clone();
    for statement in suite {
        match statement {
            Stmt::Return(return_stmt) => match return_stmt.value.as_deref() {
                Some(value) => match infer_expr_type(value, &local_context) {
                    Some(annotation) => inferred.push(annotation),
                    None => *unresolved = true,
                },
                None => inferred.push(String::from("None")),
            },
            Stmt::Assign(_) | Stmt::AnnAssign(_) => {
                collect_name_bindings_from_statement(source, statement, &mut local_context)
            }
            Stmt::FunctionDef(_) | Stmt::ClassDef(_) => {}
            Stmt::If(if_stmt) => {
                collect_return_annotations(
                    source,
                    &if_stmt.body,
                    &local_context,
                    inferred,
                    unresolved,
                );
                for clause in &if_stmt.elif_else_clauses {
                    collect_return_annotations(
                        source,
                        &clause.body,
                        &local_context,
                        inferred,
                        unresolved,
                    );
                }
            }
            Stmt::Try(try_stmt) => {
                collect_return_annotations(
                    source,
                    &try_stmt.body,
                    &local_context,
                    inferred,
                    unresolved,
                );
                for handler in &try_stmt.handlers {
                    let ruff_python_ast::ExceptHandler::ExceptHandler(handler) = handler;
                    collect_return_annotations(
                        source,
                        &handler.body,
                        &local_context,
                        inferred,
                        unresolved,
                    );
                }
                collect_return_annotations(
                    source,
                    &try_stmt.orelse,
                    &local_context,
                    inferred,
                    unresolved,
                );
                collect_return_annotations(
                    source,
                    &try_stmt.finalbody,
                    &local_context,
                    inferred,
                    unresolved,
                );
            }
            Stmt::Match(match_stmt) => {
                for case in &match_stmt.cases {
                    collect_return_annotations(
                        source,
                        &case.body,
                        &local_context,
                        inferred,
                        unresolved,
                    );
                }
            }
            Stmt::For(for_stmt) => {
                collect_return_annotations(
                    source,
                    &for_stmt.body,
                    &local_context,
                    inferred,
                    unresolved,
                );
                collect_return_annotations(
                    source,
                    &for_stmt.orelse,
                    &local_context,
                    inferred,
                    unresolved,
                );
            }
            Stmt::While(while_stmt) => {
                collect_return_annotations(
                    source,
                    &while_stmt.body,
                    &local_context,
                    inferred,
                    unresolved,
                );
                collect_return_annotations(
                    source,
                    &while_stmt.orelse,
                    &local_context,
                    inferred,
                    unresolved,
                );
            }
            Stmt::With(with_stmt) => collect_return_annotations(
                source,
                &with_stmt.body,
                &local_context,
                inferred,
                unresolved,
            ),
            _ => {}
        }
    }
}

fn infer_instance_attributes(
    source: &str,
    class_def: &ruff_python_ast::StmtClassDef,
    context: &StubInferenceContext,
    mode: InferredStubMode,
) -> Vec<(String, String)> {
    let mut attributes = BTreeMap::new();
    for statement in &class_def.body {
        let Stmt::FunctionDef(function) = statement else {
            continue;
        };
        if function.name.as_str() != "__init__" {
            continue;
        }
        let init_context = build_function_inference_context(
            source,
            &function.parameters,
            true,
            is_static_method(&function.decorator_list),
            context,
        );
        collect_instance_attribute_annotations(
            source,
            function.body.as_slice(),
            first_receiver_name(&function.parameters),
            &init_context,
            mode,
            &mut attributes,
        );
    }
    attributes.into_iter().collect()
}

fn collect_instance_attribute_annotations(
    source: &str,
    suite: &[Stmt],
    receiver_name: &str,
    context: &StubInferenceContext,
    mode: InferredStubMode,
    attributes: &mut BTreeMap<String, String>,
) {
    for statement in suite {
        match statement {
            Stmt::Assign(assign) => {
                let inferred = infer_expr_type(&assign.value, context)
                    .unwrap_or_else(|| missing_type_annotation(mode).to_owned());
                for target in &assign.targets {
                    if let Some(attribute) = self_attribute_name(target, receiver_name) {
                        merge_inferred_annotation(attributes, attribute, inferred.clone());
                    }
                }
            }
            Stmt::AnnAssign(assign) => {
                if let Some(attribute) = self_attribute_name(assign.target.as_ref(), receiver_name)
                {
                    let annotation = slice_range(source, assign.annotation.range())
                        .map(str::to_owned)
                        .unwrap_or_else(|| missing_type_annotation(mode).to_owned());
                    merge_inferred_annotation(attributes, attribute, annotation);
                }
            }
            Stmt::FunctionDef(_) | Stmt::ClassDef(_) => {}
            Stmt::If(if_stmt) => {
                collect_instance_attribute_annotations(
                    source,
                    &if_stmt.body,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
                for clause in &if_stmt.elif_else_clauses {
                    collect_instance_attribute_annotations(
                        source,
                        &clause.body,
                        receiver_name,
                        context,
                        mode,
                        attributes,
                    );
                }
            }
            Stmt::Try(try_stmt) => {
                collect_instance_attribute_annotations(
                    source,
                    &try_stmt.body,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
                for handler in &try_stmt.handlers {
                    let ruff_python_ast::ExceptHandler::ExceptHandler(handler) = handler;
                    collect_instance_attribute_annotations(
                        source,
                        &handler.body,
                        receiver_name,
                        context,
                        mode,
                        attributes,
                    );
                }
                collect_instance_attribute_annotations(
                    source,
                    &try_stmt.orelse,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
                collect_instance_attribute_annotations(
                    source,
                    &try_stmt.finalbody,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
            }
            Stmt::Match(match_stmt) => {
                for case in &match_stmt.cases {
                    collect_instance_attribute_annotations(
                        source,
                        &case.body,
                        receiver_name,
                        context,
                        mode,
                        attributes,
                    );
                }
            }
            Stmt::For(for_stmt) => {
                collect_instance_attribute_annotations(
                    source,
                    &for_stmt.body,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
                collect_instance_attribute_annotations(
                    source,
                    &for_stmt.orelse,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
            }
            Stmt::While(while_stmt) => {
                collect_instance_attribute_annotations(
                    source,
                    &while_stmt.body,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
                collect_instance_attribute_annotations(
                    source,
                    &while_stmt.orelse,
                    receiver_name,
                    context,
                    mode,
                    attributes,
                );
            }
            Stmt::With(with_stmt) => collect_instance_attribute_annotations(
                source,
                &with_stmt.body,
                receiver_name,
                context,
                mode,
                attributes,
            ),
            _ => {}
        }
    }
}

fn self_attribute_name<'a>(expr: &'a Expr, receiver_name: &str) -> Option<&'a str> {
    let Expr::Attribute(attribute) = expr else {
        return None;
    };
    let Expr::Name(name) = attribute.value.as_ref() else {
        return None;
    };
    (name.id.as_str() == receiver_name).then_some(attribute.attr.as_str())
}

fn merge_inferred_annotation(
    attributes: &mut BTreeMap<String, String>,
    attribute: &str,
    annotation: String,
) {
    match attributes.get(attribute) {
        Some(existing) if existing == &annotation => {}
        Some(existing) => {
            attributes.insert(
                attribute.to_owned(),
                normalize_union_types(vec![existing.clone(), annotation])
                    .unwrap_or_else(|| String::from("unknown")),
            );
        }
        None => {
            attributes.insert(attribute.to_owned(), annotation);
        }
    }
}

fn infer_expr_type(expr: &Expr, context: &StubInferenceContext) -> Option<String> {
    match expr {
        Expr::Name(name) => context.value_bindings.get(name.id.as_str()).cloned(),
        Expr::Attribute(attribute) => {
            let Expr::Name(name) = attribute.value.as_ref() else {
                return None;
            };
            if context.receiver_name.as_deref() == Some(name.id.as_str()) {
                return context.instance_attributes.get(attribute.attr.as_str()).cloned();
            }
            None
        }
        Expr::NumberLiteral(_) => Some(String::from("int")),
        Expr::StringLiteral(_) => Some(String::from("str")),
        Expr::BooleanLiteral(_) => Some(String::from("bool")),
        Expr::NoneLiteral(_) => Some(String::from("None")),
        Expr::Compare(_) => Some(String::from("bool")),
        Expr::UnaryOp(unary) if unary.op == ruff_python_ast::UnaryOp::Not => {
            Some(String::from("bool"))
        }
        Expr::BoolOp(bool_op) => normalize_union_types(
            bool_op.values.iter().filter_map(|value| infer_expr_type(value, context)).collect(),
        ),
        Expr::BinOp(bin_op) => infer_binop_type(bin_op, context),
        Expr::List(list) => Some(format!(
            "list[{}]",
            normalize_union_types(
                list.elts.iter().filter_map(|value| infer_expr_type(value, context)).collect(),
            )
            .unwrap_or_else(|| String::from("unknown"))
        )),
        Expr::Tuple(tuple) => Some(if tuple.elts.is_empty() {
            String::from("tuple[()]")
        } else {
            format!(
                "tuple[{}]",
                tuple
                    .elts
                    .iter()
                    .map(|value| infer_expr_type(value, context)
                        .unwrap_or_else(|| String::from("unknown")))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }),
        Expr::Set(set) => Some(format!(
            "set[{}]",
            normalize_union_types(
                set.elts.iter().filter_map(|value| infer_expr_type(value, context)).collect(),
            )
            .unwrap_or_else(|| String::from("unknown"))
        )),
        Expr::Dict(dict) => {
            let mut keys = Vec::new();
            let mut values = Vec::new();
            for item in &dict.items {
                let key = item.key.as_ref()?;
                keys.push(infer_expr_type(key, context).unwrap_or_else(|| String::from("unknown")));
                values.push(
                    infer_expr_type(&item.value, context)
                        .unwrap_or_else(|| String::from("unknown")),
                );
            }
            Some(format!(
                "dict[{}, {}]",
                normalize_union_types(keys).unwrap_or_else(|| String::from("unknown")),
                normalize_union_types(values).unwrap_or_else(|| String::from("unknown"))
            ))
        }
        Expr::Call(call) => infer_call_type(call, context),
        _ => None,
    }
}

fn infer_call_type(
    call: &ruff_python_ast::ExprCall,
    context: &StubInferenceContext,
) -> Option<String> {
    match call.func.as_ref() {
        Expr::Name(name) => match name.id.as_str() {
            "list" | "dict" | "set" | "tuple" | "int" | "float" | "str" | "bytes" | "bool" => {
                Some(name.id.as_str().to_owned())
            }
            other if context.class_names.contains(other) => Some(other.to_owned()),
            _ => None,
        },
        _ => None,
    }
}

fn infer_binop_type(
    bin_op: &ruff_python_ast::ExprBinOp,
    context: &StubInferenceContext,
) -> Option<String> {
    let left = infer_expr_type(&bin_op.left, context)?;
    let right = infer_expr_type(&bin_op.right, context)?;
    match bin_op.op {
        ruff_python_ast::Operator::Add => {
            if left == "str" && right == "str" {
                return Some(String::from("str"));
            }
            if is_numeric_type(&left) && is_numeric_type(&right) {
                return Some(join_numeric_type(&left, &right));
            }
            if let (Some((left_head, left_args)), Some((right_head, right_args))) =
                (split_generic_type(&left), split_generic_type(&right))
            {
                return match (left_head.as_str(), right_head.as_str()) {
                    ("list", "list") if left_args.len() == 1 && right_args.len() == 1 => {
                        Some(format!(
                            "list[{}]",
                            normalize_union_types(vec![
                                left_args[0].clone(),
                                right_args[0].clone()
                            ])
                            .unwrap_or_else(|| String::from("unknown"))
                        ))
                    }
                    ("tuple", "tuple") => {
                        let mut args = left_args;
                        args.extend(right_args);
                        Some(format!("tuple[{}]", args.join(", ")))
                    }
                    _ => None,
                };
            }
            None
        }
        ruff_python_ast::Operator::BitOr => {
            normalize_union_types(vec![left, right]).map(|annotation| format!("type[{annotation}]"))
        }
        _ => None,
    }
}

fn is_numeric_type(text: &str) -> bool {
    matches!(text, "int" | "float" | "complex")
}

fn join_numeric_type(left: &str, right: &str) -> String {
    if left == "complex" || right == "complex" {
        String::from("complex")
    } else if left == "float" || right == "float" {
        String::from("float")
    } else {
        String::from("int")
    }
}

fn split_generic_type(text: &str) -> Option<(String, Vec<String>)> {
    let (head, inner) = text.split_once('[')?;
    let inner = inner.strip_suffix(']')?;
    Some((head.to_owned(), inner.split(',').map(|part| part.trim().to_owned()).collect()))
}

fn normalize_union_types(types: Vec<String>) -> Option<String> {
    let mut unique = Vec::new();
    for value in types.into_iter().filter(|value| !value.is_empty()) {
        if !unique.contains(&value) {
            unique.push(value);
        }
    }
    if unique.is_empty() { None } else { Some(unique.join(" | ")) }
}

fn slice_range(source: &str, range: ruff_text_size::TextRange) -> Option<&str> {
    source.get(range.start().to_usize()..range.end().to_usize())
}

#[derive(Debug, Clone, Default)]
struct LoweredStubContext {
    value_overrides: BTreeMap<usize, String>,
    callable_overrides: BTreeMap<usize, LoweredCallableOverride>,
    synthetic_methods: BTreeMap<usize, Vec<StubSyntheticMethod>>,
    sealed_classes: BTreeMap<usize, StubSealedClass>,
    guarded_declaration_lines: BTreeSet<usize>,
}

#[derive(Debug, Clone)]
struct LoweredCallableOverride {
    params: Vec<FunctionParam>,
    returns: Option<String>,
    use_async_syntax: bool,
    drop_non_builtin_decorators: bool,
}

impl LoweredStubContext {
    fn from_module(module: &LoweredModule, context: &TypePythonStubContext) -> Self {
        let mut lowered = Self::default();
        for override_line in &context.value_overrides {
            lowered.value_overrides.insert(
                original_to_lowered_line(module, override_line.line),
                override_line.annotation.clone(),
            );
        }
        for override_line in &context.callable_overrides {
            lowered.callable_overrides.insert(
                original_to_lowered_line(module, override_line.line),
                LoweredCallableOverride {
                    params: override_line.params.clone(),
                    returns: override_line.returns.clone(),
                    use_async_syntax: override_line.use_async_syntax,
                    drop_non_builtin_decorators: override_line.drop_non_builtin_decorators,
                },
            );
        }
        for method in &context.synthetic_methods {
            lowered
                .synthetic_methods
                .entry(original_to_lowered_line(module, method.class_line))
                .or_default()
                .push(method.clone());
        }
        for sealed_class in &context.sealed_classes {
            lowered
                .sealed_classes
                .insert(original_to_lowered_line(module, sealed_class.line), sealed_class.clone());
        }
        lowered.guarded_declaration_lines = context
            .guarded_declaration_lines
            .iter()
            .map(|line| original_to_lowered_line(module, *line))
            .collect();
        lowered
    }
}

fn original_to_lowered_line(module: &LoweredModule, original_line: usize) -> usize {
    module
        .source_map
        .iter()
        .find(|entry| entry.original_line == original_line)
        .map(|entry| entry.lowered_line)
        .unwrap_or(original_line)
}

#[derive(Debug)]
struct StubEdit {
    start_line: usize,
    end_line: usize,
    replacement: Option<String>,
}

fn collect_authoritative_stub_edits(
    source: &str,
    suite: &[Stmt],
    context: &LoweredStubContext,
    edits: &mut Vec<StubEdit>,
) {
    let overloaded_names: std::collections::BTreeSet<_> = suite
        .iter()
        .filter_map(|statement| match statement {
            Stmt::FunctionDef(function)
                if function.decorator_list.iter().any(is_overload_decorator) =>
            {
                Some(function.name.as_str().to_owned())
            }
            _ => None,
        })
        .collect();

    for statement in suite {
        match statement {
            Stmt::Import(_) | Stmt::ImportFrom(_) => {}
            Stmt::TypeAlias(type_alias) => {
                let start_line = offset_to_line(source, type_alias.range.start().to_usize());
                let end_offset = type_alias.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(type_alias.range.start().to_usize()));
                edits.push(StubEdit {
                    start_line,
                    end_line,
                    replacement: slice_range(source, type_alias.range()).map(str::to_owned),
                });
            }
            Stmt::FunctionDef(function) => {
                let function_line = offset_to_line(source, function.name.range.start().to_usize());
                let start_line = function
                    .decorator_list
                    .first()
                    .map(|decorator| offset_to_line(source, decorator.range().start().to_usize()))
                    .unwrap_or(function_line);
                let end_offset = function.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(function.range.start().to_usize()));
                let replacement = if function.decorator_list.iter().any(is_overload_decorator) {
                    Some(render_authoritative_function_stub(source, function, context))
                } else if overloaded_names.contains(function.name.as_str()) {
                    None
                } else {
                    Some(render_authoritative_function_stub(source, function, context))
                };
                edits.push(StubEdit { start_line, end_line, replacement });
            }
            Stmt::AnnAssign(assign) => {
                let start_line = offset_to_line(source, assign.range.start().to_usize());
                let replacement = render_authoritative_annotated_assignment_stub(source, assign);
                edits.push(StubEdit { start_line, end_line: start_line, replacement });
            }
            Stmt::Assign(assign) => {
                let start_line = offset_to_line(source, assign.range.start().to_usize());
                let end_offset = assign.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(assign.range.start().to_usize()));
                let replacement = render_authoritative_assignment_stub(source, assign, context);
                edits.push(StubEdit { start_line, end_line, replacement });
            }
            Stmt::ClassDef(class_def) => {
                let class_line = offset_to_line(source, class_def.name.range.start().to_usize());
                let start_line = class_def
                    .decorator_list
                    .first()
                    .map(|decorator| offset_to_line(source, decorator.range().start().to_usize()))
                    .unwrap_or(class_line);
                let end_offset = class_def.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(class_def.range.start().to_usize()));
                edits.push(StubEdit {
                    start_line,
                    end_line,
                    replacement: Some(render_authoritative_class_stub(source, class_def, context)),
                });
            }
            Stmt::Expr(_) | Stmt::Pass(_) => {
                let start_line = offset_to_line(source, statement.range().start().to_usize());
                let end_offset = statement.range().end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(statement.range().start().to_usize()));
                edits.push(StubEdit { start_line, end_line, replacement: None });
            }
            _ => {
                let start_line = offset_to_line(source, statement.range().start().to_usize());
                let end_offset = statement.range().end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(statement.range().start().to_usize()));
                edits.push(StubEdit { start_line, end_line, replacement: None });
            }
        }
    }
}

fn render_authoritative_function_stub(
    source: &str,
    function: &ruff_python_ast::StmtFunctionDef,
    context: &LoweredStubContext,
) -> String {
    let function_line = offset_to_line(source, function.name.range.start().to_usize());
    if let Some(override_signature) = context.callable_overrides.get(&function_line) {
        let indentation =
            leading_indent(source.lines().nth(function_line.saturating_sub(1)).unwrap_or_default());
        let mut parts = if override_signature.drop_non_builtin_decorators {
            builtin_decorator_lines(source, &function.decorator_list, &indentation)
        } else {
            decorator_lines(
                source,
                &function.decorator_list,
                function.name.range.start().to_usize(),
            )
        };
        parts.push(format_function_stub_signature(
            &indentation,
            function.name.as_str(),
            &override_signature.params,
            override_signature.returns.as_deref(),
            override_signature.use_async_syntax,
        ));
        return parts.join("\n");
    }
    let mut parts =
        decorator_lines(source, &function.decorator_list, function.name.range.start().to_usize());
    parts.push(rewrite_stub_function_signature(source, function));
    parts.join("\n")
}

fn render_authoritative_class_stub(
    source: &str,
    class_def: &ruff_python_ast::StmtClassDef,
    context: &LoweredStubContext,
) -> String {
    let indentation = leading_indent(
        source
            .lines()
            .nth(offset_to_line(source, class_def.name.range.start().to_usize()).saturating_sub(1))
            .unwrap_or_default(),
    );
    let decorators = builtin_decorator_lines(source, &class_def.decorator_list, &indentation);
    let header =
        source_header_text(source, class_def.name.range.start().to_usize(), &class_def.body)
            .trim_end()
            .to_owned();
    let indent = format!("{}    ", indentation);
    let class_line = offset_to_line(source, class_def.name.range.start().to_usize());
    let mut body_lines = render_authoritative_class_body(source, class_def, context, &indent);
    let sealed_comment = context
        .sealed_classes
        .get(&class_line)
        .map(|sealed| render_sealed_stub_comment(sealed, &indentation));

    if let Some(extra_methods) = context.synthetic_methods.get(&class_line) {
        for method in extra_methods {
            body_lines.push(render_synthetic_method_stub(method, &indent));
        }
    }

    let mut lines = decorators;
    if let Some(sealed_comment) = sealed_comment {
        lines.push(sealed_comment);
    }
    if body_lines.is_empty() {
        let header_has_inline_comment =
            header.lines().last().is_some_and(|line| line.contains('#'));
        if header_has_inline_comment {
            lines.push(header);
            lines.push(format!("{indent}..."));
        } else {
            lines.push(rewrite_stub_header_text(&header));
        }
        lines.join("\n")
    } else {
        lines.push(header);
        lines.push(body_lines.join("\n"));
        lines.join("\n")
    }
}

fn render_sealed_stub_comment(sealed: &StubSealedClass, indentation: &str) -> String {
    let members = if sealed.members.is_empty() { String::new() } else { sealed.members.join(", ") };
    format!("{indentation}# tpy:sealed {} -> {{{members}}}", sealed.name)
}

fn render_authoritative_class_body(
    source: &str,
    class_def: &ruff_python_ast::StmtClassDef,
    context: &LoweredStubContext,
    indent: &str,
) -> Vec<String> {
    let overloaded_names: std::collections::BTreeSet<_> = class_def
        .body
        .iter()
        .filter_map(|statement| match statement {
            Stmt::FunctionDef(function)
                if function.decorator_list.iter().any(is_overload_decorator) =>
            {
                Some(function.name.as_str().to_owned())
            }
            _ => None,
        })
        .collect();
    let mut body_lines = Vec::new();

    for statement in &class_def.body {
        match statement {
            Stmt::AnnAssign(assign) => {
                if let Some(replacement) =
                    render_authoritative_annotated_assignment_stub(source, assign)
                {
                    body_lines.push(indent_block_lines(&replacement, indent));
                }
            }
            Stmt::Assign(assign) => {
                if let Some(replacement) =
                    render_authoritative_assignment_stub(source, assign, context)
                {
                    body_lines.push(indent_block_lines(&replacement, indent));
                }
            }
            Stmt::FunctionDef(function) => {
                if !function.decorator_list.iter().any(is_overload_decorator)
                    && overloaded_names.contains(function.name.as_str())
                {
                    continue;
                }
                body_lines.push(render_authoritative_function_stub(source, function, context));
            }
            Stmt::ClassDef(nested) => {
                body_lines.push(render_authoritative_class_stub(source, nested, context));
            }
            _ => {}
        }
    }

    body_lines
}

fn indent_block_lines(block: &str, indentation: &str) -> String {
    block.lines().map(|line| format!("{indentation}{line}")).collect::<Vec<_>>().join("\n")
}

fn render_authoritative_annotated_assignment_stub(
    source: &str,
    assign: &ruff_python_ast::StmtAnnAssign,
) -> Option<String> {
    if source
        .lines()
        .nth(offset_to_line(source, assign.range.start().to_usize()).saturating_sub(1))
        .is_some_and(|line| line.contains("TypeAlias ="))
    {
        return source_stmt_text(source, assign.range());
    }
    render_annotated_assignment_stub(source, assign)
}

fn render_authoritative_assignment_stub(
    source: &str,
    assign: &ruff_python_ast::StmtAssign,
    context: &LoweredStubContext,
) -> Option<String> {
    let start_line = offset_to_line(source, assign.range.start().to_usize());
    if let Some(statement_text) = source_stmt_text(source, assign.range())
        && statement_text.contains("TypeAlias =")
    {
        return Some(statement_text);
    }
    if let Some(annotation) = context.value_overrides.get(&start_line) {
        let mut lines = Vec::new();
        for target in &assign.targets {
            let Expr::Name(name) = target else {
                continue;
            };
            lines.push(format!("{}: {}", name.id.as_str(), annotation));
        }
        if !lines.is_empty() {
            return Some(lines.join("\n"));
        }
    }
    render_assignment_stub(
        source,
        &assign.targets,
        &assign.value,
        &StubInferenceContext::default(),
        InferredStubMode::Shadow,
    )
}

fn render_synthetic_method_stub(method: &StubSyntheticMethod, indentation: &str) -> String {
    let mut lines = Vec::new();
    lines.extend(method_decorator_lines(method.method_kind, indentation));
    lines.push(format_function_stub_signature(
        indentation,
        &method.name,
        &method.params,
        method.returns.as_deref(),
        false,
    ));
    lines.join("\n")
}

fn method_decorator_lines(method_kind: MethodKind, indentation: &str) -> Vec<String> {
    match method_kind {
        MethodKind::Class => vec![format!("{indentation}@classmethod")],
        MethodKind::Static => vec![format!("{indentation}@staticmethod")],
        MethodKind::Property => vec![format!("{indentation}@property")],
        MethodKind::PropertySetter => vec![format!("{indentation}@property.setter")],
        MethodKind::Instance => Vec::new(),
    }
}

fn format_function_stub_signature(
    indentation: &str,
    name: &str,
    params: &[FunctionParam],
    returns: Option<&str>,
    use_async_syntax: bool,
) -> String {
    let prefix = if use_async_syntax { "async def" } else { "def" };
    format!(
        "{indentation}{prefix} {name}({}) -> {}: ...",
        format_stub_params(params),
        returns.unwrap_or("None")
    )
}

fn format_stub_params(params: &[FunctionParam]) -> String {
    let mut rendered = Vec::new();
    let positional_only_count = params.iter().filter(|param| param.positional_only).count();
    let has_variadic = params.iter().any(|param| param.variadic);
    let keyword_only_index = params.iter().position(|param| param.keyword_only);

    for (index, param) in params.iter().enumerate() {
        if keyword_only_index == Some(index) && !has_variadic {
            rendered.push(String::from("*"));
        }
        let mut part = match &param.annotation {
            Some(annotation) => format!("{}: {}", param.name, annotation),
            None => param.name.clone(),
        };
        if param.has_default {
            part.push_str(" = ...");
        }
        if param.keyword_variadic {
            part = format!("**{part}");
        } else if param.variadic {
            part = format!("*{part}");
        }
        rendered.push(part);
        if positional_only_count > 0 && index + 1 == positional_only_count {
            rendered.push(String::from("/"));
        }
    }

    rendered.join(", ")
}

fn builtin_decorator_lines(
    source: &str,
    decorators: &[ruff_python_ast::Decorator],
    indentation: &str,
) -> Vec<String> {
    decorators
        .iter()
        .filter(|decorator| is_stub_surface_decorator(&decorator.expression))
        .filter_map(|decorator| {
            slice_range(source, decorator.expression.range())
                .map(|expression| format!("{indentation}@{expression}"))
        })
        .collect()
}

fn is_stub_surface_decorator(expression: &Expr) -> bool {
    match expression {
        Expr::Name(name) => matches!(
            name.id.as_str(),
            "overload"
                | "staticmethod"
                | "classmethod"
                | "property"
                | "final"
                | "override"
                | "deprecated"
        ),
        Expr::Attribute(attribute) => {
            matches!(
                attribute.attr.as_str(),
                "overload" | "staticmethod" | "classmethod" | "setter" | "deprecated"
            ) || matches!(attribute.attr.as_str(), "property")
        }
        Expr::Call(call) => is_stub_surface_decorator(call.func.as_ref()),
        _ => false,
    }
}

fn source_stmt_text(source: &str, range: ruff_text_size::TextRange) -> Option<String> {
    let start_line = offset_to_line(source, range.start().to_usize());
    let end_offset = range.end().to_usize().saturating_sub(1);
    let end_line = offset_to_line(source, end_offset.max(range.start().to_usize()));
    let text = source
        .lines()
        .skip(start_line.saturating_sub(1))
        .take(end_line.saturating_sub(start_line) + 1)
        .collect::<Vec<_>>()
        .join("\n");
    (!text.is_empty()).then_some(text)
}

#[allow(dead_code)]
fn collect_stub_edits(source: &str, suite: &[Stmt], edits: &mut Vec<StubEdit>) {
    let overloaded_names: std::collections::BTreeSet<_> = suite
        .iter()
        .filter_map(|statement| match statement {
            Stmt::FunctionDef(function)
                if function.decorator_list.iter().any(is_overload_decorator) =>
            {
                Some(function.name.as_str().to_owned())
            }
            _ => None,
        })
        .collect();

    for statement in suite {
        match statement {
            Stmt::FunctionDef(function) => {
                let start_line = offset_to_line(source, function.name.range.start().to_usize());
                let end_offset = function.range.end().to_usize().saturating_sub(1);
                let end_line =
                    offset_to_line(source, end_offset.max(function.range.start().to_usize()));
                edits.push(StubEdit {
                    start_line,
                    end_line,
                    replacement: if function.decorator_list.iter().any(is_overload_decorator) {
                        Some(rewrite_stub_function_signature(source, function))
                    } else if overloaded_names.contains(function.name.as_str()) {
                        None
                    } else {
                        Some(rewrite_stub_function_signature(source, function))
                    },
                });
            }
            Stmt::AnnAssign(assign) => {
                if let Some(replacement) = rewrite_stub_annotated_assignment_line(
                    source
                        .lines()
                        .nth(offset_to_line(source, assign.range.start().to_usize()) - 1)
                        .unwrap_or(""),
                ) {
                    let start_line = offset_to_line(source, assign.range.start().to_usize());
                    edits.push(StubEdit {
                        start_line,
                        end_line: start_line,
                        replacement: Some(replacement),
                    });
                }
            }
            Stmt::ClassDef(class_def) => {
                if is_empty_stub_class_body(&class_def.body) {
                    let start_line =
                        offset_to_line(source, class_def.name.range.start().to_usize());
                    let end_offset = class_def.range.end().to_usize().saturating_sub(1);
                    let end_line =
                        offset_to_line(source, end_offset.max(class_def.range.start().to_usize()));
                    edits.push(StubEdit {
                        start_line,
                        end_line,
                        replacement: Some(rewrite_stub_class_line(source, class_def)),
                    });
                } else {
                    collect_stub_edits(source, &class_def.body, edits)
                }
            }
            _ => {}
        }
    }
}

fn rewrite_stub_function_signature(
    source: &str,
    function: &ruff_python_ast::StmtFunctionDef,
) -> String {
    let header = source_header_text(source, function.name.range.start().to_usize(), &function.body);
    rewrite_stub_header_text(&header)
}

fn rewrite_stub_header_text(header: &str) -> String {
    let trimmed = header.trim_end();
    if trimmed.contains(": ...") {
        trimmed.to_owned()
    } else if trimmed.ends_with(':') {
        format!("{trimmed} ...")
    } else {
        trimmed.to_owned()
    }
}

#[allow(dead_code)]
fn rewrite_stub_annotated_assignment_line(line: &str) -> Option<String> {
    if line.contains("TypeAlias =") {
        return None;
    }
    let (head, _) = line.split_once('=')?;
    Some(head.trim_end().to_owned())
}

#[allow(dead_code)]
fn rewrite_stub_class_line(source: &str, class_def: &ruff_python_ast::StmtClassDef) -> String {
    let header =
        source_header_text(source, class_def.name.range.start().to_usize(), &class_def.body);
    rewrite_stub_header_text(&header)
}

fn source_header_text(source: &str, start_offset: usize, body: &[Stmt]) -> String {
    let start_line = offset_to_line(source, start_offset);
    let header_end_line = body
        .first()
        .map(|statement| {
            offset_to_line(source, statement.range().start().to_usize()).saturating_sub(1)
        })
        .unwrap_or(start_line);
    source
        .lines()
        .skip(start_line.saturating_sub(1))
        .take(header_end_line.saturating_sub(start_line) + 1)
        .collect::<Vec<_>>()
        .join("\n")
}

fn inject_guarded_declaration_stubs(
    source: &str,
    suite: &[Stmt],
    context: &LoweredStubContext,
    rewritten: &str,
) -> String {
    if context.guarded_declaration_lines.is_empty() {
        return rewritten.to_owned();
    }
    let extras = collect_guarded_declaration_stub_blocks(source, suite, context);
    if extras.is_empty() {
        return rewritten.to_owned();
    }

    let mut lines = rewritten.lines().map(str::to_owned).collect::<Vec<_>>();
    let insert_at = lines
        .iter()
        .position(|line| {
            let trimmed = line.trim();
            !trimmed.is_empty() && !trimmed.starts_with("from ") && !trimmed.starts_with("import ")
        })
        .unwrap_or(lines.len());
    lines.splice(insert_at..insert_at, extras);
    lines.join("\n")
}

fn collect_guarded_declaration_stub_blocks(
    source: &str,
    suite: &[Stmt],
    context: &LoweredStubContext,
) -> Vec<String> {
    let mut blocks = Vec::new();
    for statement in suite {
        match statement {
            Stmt::If(if_stmt) => {
                blocks.extend(collect_guarded_declaration_stub_blocks(
                    source,
                    &if_stmt.body,
                    context,
                ));
                for clause in &if_stmt.elif_else_clauses {
                    blocks.extend(collect_guarded_declaration_stub_blocks(
                        source,
                        &clause.body,
                        context,
                    ));
                }
            }
            Stmt::Try(try_stmt) => {
                blocks.extend(collect_guarded_declaration_stub_blocks(
                    source,
                    &try_stmt.body,
                    context,
                ));
                for handler in &try_stmt.handlers {
                    let ruff_python_ast::ExceptHandler::ExceptHandler(handler) = handler;
                    blocks.extend(collect_guarded_declaration_stub_blocks(
                        source,
                        &handler.body,
                        context,
                    ));
                }
                blocks.extend(collect_guarded_declaration_stub_blocks(
                    source,
                    &try_stmt.orelse,
                    context,
                ));
                blocks.extend(collect_guarded_declaration_stub_blocks(
                    source,
                    &try_stmt.finalbody,
                    context,
                ));
            }
            Stmt::ClassDef(class_def) => {
                let line = offset_to_line(source, class_def.name.range.start().to_usize());
                if context.guarded_declaration_lines.contains(&line) {
                    blocks.push(dedent_stub_block(&render_authoritative_class_stub(
                        source, class_def, context,
                    )));
                }
            }
            Stmt::FunctionDef(function) => {
                let line = offset_to_line(source, function.name.range.start().to_usize());
                if context.guarded_declaration_lines.contains(&line) {
                    blocks.push(dedent_stub_block(&render_authoritative_function_stub(
                        source, function, context,
                    )));
                }
            }
            Stmt::AnnAssign(assign) => {
                let line = offset_to_line(source, assign.range.start().to_usize());
                if context.guarded_declaration_lines.contains(&line)
                    && let Some(block) =
                        render_authoritative_annotated_assignment_stub(source, assign)
                {
                    blocks.push(dedent_stub_block(&block));
                }
            }
            _ => {}
        }
    }
    blocks
}

fn dedent_stub_block(block: &str) -> String {
    let indent = block
        .lines()
        .find(|line| !line.trim().is_empty())
        .map(|line| line.chars().take_while(|character| character.is_whitespace()).count())
        .unwrap_or(0);
    block
        .lines()
        .map(|line| {
            if line.trim().is_empty() { String::new() } else { line.chars().skip(indent).collect() }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn normalize_emitted_stub_intrinsic_types(source: &str) -> Result<String, io::Error> {
    let parsed = parse_module(source).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "unable to parse stub source for intrinsic type normalization: {}",
                error.error
            ),
        )
    })?;
    let unknown_comments = collect_unknown_boundary_comments(source, parsed.suite());
    let mut replacements = Vec::new();
    collect_intrinsic_type_replacements(source, parsed.suite(), &mut replacements);
    replacements
        .sort_by(|(left_range, _), (right_range, _)| right_range.start().cmp(&left_range.start()));

    let mut normalized = source.to_owned();
    let mut introduced_any = false;
    for (range, replacement) in replacements {
        if let Some(existing) = slice_range(&normalized, range)
            && existing == replacement
        {
            continue;
        }
        introduced_any |= replacement.contains("Any");
        normalized.replace_range(range.start().to_usize()..range.end().to_usize(), &replacement);
    }
    if introduced_any && !has_typing_any_import(&normalized) {
        normalized = format!("from typing import Any\n{normalized}");
    }
    normalized = insert_unknown_boundary_comments(
        &normalized,
        &unknown_comments,
        usize::from(introduced_any),
    );
    Ok(normalized)
}

fn collect_intrinsic_type_replacements(
    source: &str,
    suite: &[Stmt],
    replacements: &mut Vec<(ruff_text_size::TextRange, String)>,
) {
    for statement in suite {
        match statement {
            Stmt::FunctionDef(function) => {
                collect_parameter_intrinsic_type_replacements(
                    source,
                    &function.parameters,
                    replacements,
                );
                if let Some(returns) = function.returns.as_deref()
                    && let Some(replacement) = normalize_intrinsic_type_text(
                        slice_range(source, returns.range()).unwrap_or_default(),
                    )
                {
                    replacements.push((returns.range(), replacement));
                }
            }
            Stmt::AnnAssign(assign) => {
                if let Some(replacement) = normalize_intrinsic_type_text(
                    slice_range(source, assign.annotation.range()).unwrap_or_default(),
                ) {
                    replacements.push((assign.annotation.range(), replacement));
                }
                if let Some(value) = assign.value.as_deref()
                    && slice_range(source, assign.annotation.range())
                        .is_some_and(|annotation| annotation.trim_end() == "TypeAlias")
                    && let Some(replacement) = normalize_intrinsic_type_text(
                        slice_range(source, value.range()).unwrap_or_default(),
                    )
                {
                    replacements.push((value.range(), replacement));
                }
            }
            Stmt::ClassDef(class_def) => {
                if let Some(arguments) = class_def.arguments.as_ref() {
                    for argument in &arguments.args {
                        if let Some(replacement) = normalize_intrinsic_type_text(
                            slice_range(source, argument.range()).unwrap_or_default(),
                        ) {
                            replacements.push((argument.range(), replacement));
                        }
                    }
                }
                collect_intrinsic_type_replacements(source, &class_def.body, replacements);
            }
            _ => {}
        }
    }
}

fn collect_parameter_intrinsic_type_replacements(
    source: &str,
    parameters: &ruff_python_ast::Parameters,
    replacements: &mut Vec<(ruff_text_size::TextRange, String)>,
) {
    let mut collect_annotation = |annotation: Option<&Expr>| {
        if let Some(annotation) = annotation
            && let Some(replacement) = normalize_intrinsic_type_text(
                slice_range(source, annotation.range()).unwrap_or_default(),
            )
        {
            replacements.push((annotation.range(), replacement));
        }
    };
    for parameter in &parameters.posonlyargs {
        collect_annotation(parameter.annotation());
    }
    for parameter in &parameters.args {
        collect_annotation(parameter.annotation());
    }
    if let Some(parameter) = parameters.vararg.as_ref() {
        collect_annotation(parameter.annotation());
    }
    for parameter in &parameters.kwonlyargs {
        collect_annotation(parameter.annotation());
    }
    if let Some(parameter) = parameters.kwarg.as_ref() {
        collect_annotation(parameter.annotation());
    }
}

fn normalize_intrinsic_type_text(text: &str) -> Option<String> {
    let mut normalized = String::new();
    let mut token = String::new();
    let mut changed = false;

    let flush_token = |token: &mut String, normalized: &mut String, changed: &mut bool| {
        if token.is_empty() {
            return;
        }
        match token.as_str() {
            "unknown" => {
                normalized.push_str("object");
                *changed = true;
            }
            "dynamic" => {
                normalized.push_str("Any");
                *changed = true;
            }
            _ => normalized.push_str(token),
        }
        token.clear();
    };

    for character in text.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            token.push(character);
        } else {
            flush_token(&mut token, &mut normalized, &mut changed);
            normalized.push(character);
        }
    }
    flush_token(&mut token, &mut normalized, &mut changed);

    changed.then_some(normalized)
}

fn has_typing_any_import(source: &str) -> bool {
    source.lines().any(|line| {
        let trimmed = line.trim();
        trimmed == "from typing import Any"
            || (trimmed.starts_with("from typing import ") && trimmed.contains("Any"))
    })
}

fn collect_unknown_boundary_comments(source: &str, suite: &[Stmt]) -> Vec<(usize, String)> {
    let mut comments = Vec::new();
    for statement in suite {
        match statement {
            Stmt::FunctionDef(function) => {
                let has_unknown = function
                    .returns
                    .as_deref()
                    .and_then(|returns| slice_range(source, returns.range()))
                    .is_some_and(type_text_contains_unknown)
                    || parameters_contain_unknown(source, &function.parameters);
                if has_unknown {
                    comments.push((
                        offset_to_line(source, function.name.range.start().to_usize()),
                        format!("# tpy:unknown {}", function.name.as_str()),
                    ));
                }
            }
            Stmt::AnnAssign(assign) => {
                let line = offset_to_line(source, assign.range.start().to_usize());
                if slice_range(source, assign.annotation.range())
                    .is_some_and(|annotation| annotation.trim_end() == "TypeAlias")
                    && assign
                        .value
                        .as_deref()
                        .and_then(|value| slice_range(source, value.range()))
                        .is_some_and(type_text_contains_unknown)
                    && let Expr::Name(name) = assign.target.as_ref()
                {
                    comments.push((line, format!("# tpy:unknown {}", name.id.as_str())));
                } else if slice_range(source, assign.annotation.range())
                    .is_some_and(type_text_contains_unknown)
                    && let Expr::Name(name) = assign.target.as_ref()
                {
                    comments.push((line, format!("# tpy:unknown {}", name.id.as_str())));
                }
            }
            Stmt::ClassDef(class_def) => {
                comments.extend(collect_unknown_boundary_comments(source, &class_def.body));
            }
            _ => {}
        }
    }
    comments
}

fn parameters_contain_unknown(source: &str, parameters: &ruff_python_ast::Parameters) -> bool {
    let contains_unknown = |annotation: Option<&Expr>| {
        annotation
            .and_then(|annotation| slice_range(source, annotation.range()))
            .is_some_and(type_text_contains_unknown)
    };
    parameters.posonlyargs.iter().any(|parameter| contains_unknown(parameter.annotation()))
        || parameters.args.iter().any(|parameter| contains_unknown(parameter.annotation()))
        || parameters
            .vararg
            .as_ref()
            .is_some_and(|parameter| contains_unknown(parameter.annotation()))
        || parameters.kwonlyargs.iter().any(|parameter| contains_unknown(parameter.annotation()))
        || parameters
            .kwarg
            .as_ref()
            .is_some_and(|parameter| contains_unknown(parameter.annotation()))
}

fn type_text_contains_unknown(text: &str) -> bool {
    contains_type_token(text, "unknown")
}

fn contains_type_token(text: &str, token: &str) -> bool {
    let mut current = String::new();
    for character in text.chars().chain(std::iter::once(' ')) {
        if character.is_ascii_alphanumeric() || character == '_' {
            current.push(character);
            continue;
        }
        if current == token {
            return true;
        }
        current.clear();
    }
    false
}

fn insert_unknown_boundary_comments(
    source: &str,
    comments: &[(usize, String)],
    line_offset: usize,
) -> String {
    if comments.is_empty() {
        return source.to_owned();
    }
    let mut lines = source.lines().map(str::to_owned).collect::<Vec<_>>();
    let mut comments = comments.to_vec();
    comments.sort_by(|left, right| right.0.cmp(&left.0));
    for (line, comment) in comments {
        let insert_at = line.saturating_sub(1) + line_offset;
        if insert_at <= lines.len() {
            lines.insert(insert_at, comment);
        }
    }
    let mut rewritten = lines.join("\n");
    if source.ends_with('\n') {
        rewritten.push('\n');
    }
    rewritten
}

#[allow(dead_code)]
fn is_empty_stub_class_body(body: &[Stmt]) -> bool {
    body.iter().all(|statement| match statement {
        Stmt::Pass(_) => true,
        Stmt::Expr(expr) => {
            matches!(expr.value.as_ref(), Expr::StringLiteral(_) | Expr::EllipsisLiteral(_))
        }
        _ => false,
    })
}

fn is_overload_decorator(decorator: &ruff_python_ast::Decorator) -> bool {
    match &decorator.expression {
        Expr::Name(name) => name.id.as_str() == "overload",
        Expr::Attribute(attribute) => {
            attribute.attr.as_str() == "overload"
                && matches!(attribute.value.as_ref(), Expr::Name(name) if name.id.as_str() == "typing")
        }
        _ => false,
    }
}

fn offset_to_line(source: &str, offset: usize) -> usize {
    let mut line = 1usize;

    for (index, character) in source.char_indices() {
        if index >= offset {
            break;
        }
        if character == '\n' {
            line += 1;
        }
    }

    line
}
