class PurePath:
    def __truediv__(self, other) -> PurePath: ...
    def as_posix(self) -> str: ...

class Path(PurePath):
    def read_text(self) -> str: ...
    def write_text(self, text: str) -> int: ...
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def joinpath(self, *parts) -> Path: ...
